
stages:
  - build
  - publish

variables:
  MAVEN_CLI_OPTS: "--batch-mode -DskipTests"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_IIT_HOST: docker-registry.services.iit.cnr.it
  DOCKER_GROUP: ChorChain
  DOCKER_IMAGE: ${DOCKER_IIT_HOST}/${DOCKER_GROUP}/${CI_PROJECT_NAME}

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:3-jdk-8
  script:
    - mvn $MAVEN_CLI_OPTS clean package

publish-master:
  stage: publish
  image: docker:stable
  script:
    - docker build ./ -t ${DOCKER_IMAGE}:latest
    - docker login -u "${IIT_REGISTRY_USER}" -p "${IIT_REGISTRY_PASSWORD}" $DOCKER_IIT_HOST
    - docker push ${DOCKER_IMAGE}:latest
  only:
    - master

publish-tag:
  stage: publish
  image: docker:stable
  script:
    - docker build ./ -t ${DOCKER_IMAGE}:${CI_COMMIT_TAG}
    - docker tag ${DOCKER_IMAGE}:${CI_COMMIT_TAG} ${DOCKER_IMAGE}:stable
    - docker login -u "${IIT_REGISTRY_USER}" -p "${IIT_REGISTRY_PASSWORD}" $DOCKER_IIT_HOST
    - docker push ${DOCKER_IMAGE}:${CI_COMMIT_TAG}
    - docker push ${DOCKER_IMAGE}:stable
  only:
    - tags
