version: '3.2'


services:
  mysql-docker:
    image: mysql:5.7
    hostname: mysql-docker
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: chorchain
      MYSQL_DATABASE: chorchain
      MYSQL_USER: chorchain
      MYSQL_PASSWORD: chorchain
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    healthcheck:
      test: ["CMD-SHELL", 'mysqladmin ping']
      interval: 10s
      timeout: 2s
      retries: 10
  #restart: always


  dev-blockchain:
    image: trufflesuite/ganache-cli:v6.1.6
    ports:
      - 8545:8545
    command: ["-h=0.0.0.0","--mnemonic='include poem goose genuine baby flat mom token drama harsh sadness fit'","--db ganache-db","-l 9000000000","-d 100000000","--allowUnlimitedContractSize"]

#    command: ["-d 100000000 --allowUnlimitedContractSize --db ganache-db --port 8545 -l 9000000000 --accounts 10 --mnemonic='include poem goose genuine baby flat mom token drama harsh sadness fit' --networkId 5777 -h=0.0.0.0"]

  backend:
    image: restchain-service
    hostname: backend
    environment:
      TZ: Europe/Rome
      spring.datasource.platform: mysql
      spring.jpa.generated-ddl: "true"
      spring.jpa.hibernate.ddl-auto: update
      spring.datasource.url: jdbc:mysql://mysql-docker:3306/chorchain?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      spring.datasource.username: chorchain
      spring.datasource.password: chorchain
#    ports:
#      - target: 80
#        published: 8080
#        protocol: tcp
    depends_on:
      - mysql-docker
